baseURL: https://blog.darshanrander.com
languageCode: en-us
title: Darshan's Blog
theme: PaperMod
copyright: "&copy; 2022 [Darshan Rander](https://darshanrander.com) |"
paginate: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  title: Darshan's Blog
  description: "I like to solve problems. Mostly work with app and backend technologies."
  keywords: [Blog, Darshan Rander]
  author: Darshan Rander
  images:
    - https://darshanrander.com/static/img/og-general.png
    - https://darshanrander.com/static/img/og-twitter.png
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    favicon: favicons/favicon.ico
    favicon16x16: favicons/favicon-16x16.png
    favicon32x32: favicons/favicon-32x32.png
    apple_touch_icon: favicons/apple-touch-icon.png
    safari_pinned_tab: favicons/safari-pinned-tab.svg
    disableFingerprinting: true

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B, I'm Darshan"
    Content: I like to solve problems. Mostly work with app and backend technologies.

  socialIcons:
    - name: website
      url: "https://darshanrander.com"
    - name: twitter
      url: "https://twitter.com/SirusTweets"
    - name: github
      url: "https://github.com/SirusCodes"
    - name: linkedin
      url: "https://linkedin.com/in/darshan-rander"
    - name: email
      url: "mailto:hey@darshanrander.com"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/SirusCodes/blog/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - identifier: Series
      name: Series
      url: series/
      weight: 10
    - identifier: portfolio
      name: darshanrander.com
      url: https://darshanrander.com
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
taxonomies:
  series: series
